tallas = c('m','g','S','S','m','M', 'G', 'G', 'G', 'G', 'g')
plot(tallas)
tallas_factor=factor(tallas)
plot(tallas_factor)
levels(tallas_factor)
tallas_recodificado=factor(tallas, levels=c('m','M','S','g','G'), labels=c('M','M','S','G','G'))
plot(tallas_recodificado)
tallas_ordenado=factor(tallas, ordered=TRUE, levels=c('S','M', 'm','g','G'), labels=c('S','M','M','G','G'))
plot(tallas_ordenado)
sort(tallas_recodificado)
plot(tallas_recodificado)
